version: '3.8'

services:
  movienight:
    build: .
    container_name: movienight
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "30000-30100:30000-30100/udp"
    env_file:
      - .env
    volumes:
      - sessions:/data
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sessions:
    driver: local
